### ISSUE TITLE
Sketch index page 

### ISSUE THREAD

**Issue by oscarjosecostero** [oscarjosecostero/Easyrent#3]
Here are some of the web pages that we can use as pattern to start our own.
www.century21.com
www.remax.com
www.kw.com/kw/

**Comment by oscarjosecostero** [comment]
Some more examples of real state webpages:
https://www.zillow.com/
https://www.redfin.com/
https://www.corcoran.com/

**Comment by gbrlmrllo** [comment]
https://www.rent.com.au/
https://www.rentfaster.ca

**Comment by gbrlmrllo** [comment]
This is still open, because it isn't finished at 100%

cc @oscarjosecostero @OscarlynCostero
